apiVersion: v1
kind: Service
metadata:
  name: dev-reddit-project-service
  namespace: dev-namespace
spec:
  selector:
    app: dev-reddit-project-deployment
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32111
  type: NodePort
