apiVersion: v1
kind: Service
metadata:
  name: prod-reddit-project-service
  namespace: prod-namespace
spec:
  selector:
    app: prod-reddit-project-deployment
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32112
  type: NodePort
