apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-reddit-project-deployment
  namespace: prod-namespace
  labels:
    app: prod-reddit-project-deployment
spec:
  selector:
    matchLabels:
      app: prod-reddit-project-deployment
  template:
    metadata:
      labels:
        app: prod-reddit-project-deployment
    spec:
      containers:
      - name: prod-reddit-project-deployment
        image: idrisniyi94/reddit-project:prod-fwf-1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

