apiVersion: v1
kind: Service
metadata:
  name: qa-reddit-project-service
  namespace: qa-namespace
spec:
  selector:
    app: qa-reddit-project-deployment
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32113
  type: NodePort
